SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for dendra_map_variables_tags
-- ----------------------------
DROP TABLE IF EXISTS `dendra_map_variables_tags`;
CREATE TABLE `dendra_map_variables_tags` (
  `VariableCode` varchar(255) CHARACTER SET latin1 NOT NULL,
  `tag` varchar(255) NOT NULL,
  PRIMARY KEY (`VariableCode`,`tag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of dendra_map_variables_tags
-- ----------------------------
BEGIN;
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Avg', 'ds_Aggregate_Average');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Avg', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Avg', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Avg', 'ds_Variable_Temperature');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Avg', 'dt_Unit_DegreeCelsius');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Max', 'ds_Aggregate_Maximum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Max', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Max', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Max', 'ds_Variable_Temperature');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Max', 'dt_Unit_DegreeCelsius');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Min', 'ds_Aggregate_Minimum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Min', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Min', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Min', 'ds_Variable_Temperature');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp C Min', 'dt_Unit_DegreeCelsius');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Avg', 'ds_Aggregate_Average');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Avg', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Avg', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Avg', 'ds_Variable_Temperature');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Avg', 'dt_Unit_DegreeCelsius');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Max', 'ds_Aggregate_Maximum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Max', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Max', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Max', 'ds_Variable_Temperature');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Max', 'dt_Unit_DegreeCelsius');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Min', 'ds_Aggregate_Minimum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Min', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Min', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Min', 'ds_Variable_Temperature');
INSERT INTO `dendra_map_variables_tags` VALUES ('Air Temp Delta C Min', 'dt_Unit_DegreeCelsius');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Avg', 'ds_Aggregate_Average');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Avg', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Avg', 'ds_Medium_Battery');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Avg', 'ds_Variable_Voltage');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Avg', 'dt_Unit_Volt');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Max', 'ds_Aggregate_Maximum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Max', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Max', 'ds_Medium_Battery');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Max', 'ds_Variable_Voltage');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Max', 'dt_Unit_Volt');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Min', 'ds_Aggregate_Minimum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Min', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Min', 'ds_Medium_Battery');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Min', 'ds_Variable_Voltage');
INSERT INTO `dendra_map_variables_tags` VALUES ('Battery Voltage Min', 'dt_Unit_Volt');
INSERT INTO `dendra_map_variables_tags` VALUES ('Derived Cumulative Precipitation', 'ds_Aggregate_Cumulative');
INSERT INTO `dendra_map_variables_tags` VALUES ('Derived Cumulative Precipitation', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Derived Cumulative Precipitation', 'ds_Medium_Precipitation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Derived Cumulative Precipitation', 'ds_Variable_Height');
INSERT INTO `dendra_map_variables_tags` VALUES ('Derived Cumulative Precipitation', 'dt_Unit_Millimeter');
INSERT INTO `dendra_map_variables_tags` VALUES ('Evapotranspiration', 'ds_Aggregate_Average');
INSERT INTO `dendra_map_variables_tags` VALUES ('Evapotranspiration', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Evapotranspiration', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Evapotranspiration', 'ds_Variable_Evapotranspiration');
INSERT INTO `dendra_map_variables_tags` VALUES ('Evapotranspiration', 'dt_Unit_Millimeter');
INSERT INTO `dendra_map_variables_tags` VALUES ('Fuel Moisture Per Avg', 'ds_Aggregate_Average');
INSERT INTO `dendra_map_variables_tags` VALUES ('Fuel Moisture Per Avg', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Fuel Moisture Per Avg', 'ds_Medium_Instrument');
INSERT INTO `dendra_map_variables_tags` VALUES ('Fuel Moisture Per Avg', 'ds_Variable_Moisture');
INSERT INTO `dendra_map_variables_tags` VALUES ('Fuel Moisture Per Avg', 'dt_Unit_Percent');
INSERT INTO `dendra_map_variables_tags` VALUES ('Hail Cumulative mm', 'ds_Aggregate_Cumulative');
INSERT INTO `dendra_map_variables_tags` VALUES ('Hail Cumulative mm', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Hail Cumulative mm', 'ds_Medium_Precipitation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Hail Cumulative mm', 'ds_Variable_Height');
INSERT INTO `dendra_map_variables_tags` VALUES ('Hail Cumulative mm', 'dt_Unit_Millimeter');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative cm', 'ds_Aggregate_Cumulative');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative cm', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative cm', 'ds_Medium_Precipitation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative cm', 'ds_Variable_Height');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative cm', 'dt_Unit_Centimeter');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative in.', 'ds_Aggregate_Cumulative');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative in.', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative in.', 'ds_Medium_Precipitation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative in.', 'ds_Variable_Height');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative in.', 'dt_Unit_Inch');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative mm', 'ds_Aggregate_Cumulative');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative mm', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative mm', 'ds_Medium_Precipitation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative mm', 'ds_Variable_Height');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rainfall Cumulative mm', 'dt_Unit_Millimeter');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Avg', 'ds_Aggregate_Average');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Avg', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Avg', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Avg', 'ds_Variable_RelativeHumidity');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Avg', 'dt_Unit_Percent');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Max', 'ds_Aggregate_Maximum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Max', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Max', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Max', 'ds_Variable_RelativeHumidity');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Max', 'dt_Unit_Percent');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Min', 'ds_Aggregate_Minimum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Min', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Min', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Min', 'ds_Variable_RelativeHumidity');
INSERT INTO `dendra_map_variables_tags` VALUES ('Rel Humidity Per Min', 'dt_Unit_Percent');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Avg', 'ds_Aggregate_Average');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Avg', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Avg', 'ds_Medium_Snow');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Avg', 'ds_Variable_Temperature');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Avg', 'dt_Unit_DegreeCelsius');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Max', 'ds_Aggregate_Maximum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Max', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Max', 'ds_Medium_Snow');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Max', 'ds_Variable_Temperature');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Max', 'dt_Unit_DegreeCelsius');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Min', 'ds_Aggregate_Minimum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Min', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Min', 'ds_Medium_Snow');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Min', 'ds_Variable_Temperature');
INSERT INTO `dendra_map_variables_tags` VALUES ('Snow Temp Deg C Min', 'dt_Unit_DegreeCelsius');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Moisture Pct Avg', 'ds_Aggregate_Average');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Moisture Pct Avg', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Moisture Pct Avg', 'ds_Medium_Soil');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Moisture Pct Avg', 'ds_Variable_Moisture');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Moisture Pct Avg', 'dt_Unit_Percent');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Avg', 'ds_Aggregate_Average');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Avg', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Avg', 'ds_Medium_Soil');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Avg', 'ds_Variable_Temperature');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Avg', 'dt_Unit_DegreeCelsius');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Max', 'ds_Aggregate_Maximum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Max', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Max', 'ds_Medium_Soil');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Max', 'ds_Variable_Temperature');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Max', 'dt_Unit_DegreeCelsius');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Min', 'ds_Aggregate_Minimum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Min', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Min', 'ds_Medium_Soil');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Min', 'ds_Variable_Temperature');
INSERT INTO `dendra_map_variables_tags` VALUES ('Soil Temp C Min', 'dt_Unit_DegreeCelsius');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Avg W/m^2', 'ds_Aggregate_Average');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Avg W/m^2', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Avg W/m^2', 'ds_Medium_Solar');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Avg W/m^2', 'ds_Variable_SolarRadiation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Avg W/m^2', 'dt_Unit_WattPerSquareMeter');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Max W/m^2', 'ds_Aggregate_Maximum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Max W/m^2', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Max W/m^2', 'ds_Medium_Solar');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Max W/m^2', 'ds_Variable_SolarRadiation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Max W/m^2', 'dt_Unit_WattPerSquareMeter');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Min W/m^2', 'ds_Aggregate_Minimum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Min W/m^2', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Min W/m^2', 'ds_Medium_Solar');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Min W/m^2', 'ds_Variable_SolarRadiation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Min W/m^2', 'dt_Unit_WattPerSquareMeter');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Net W/m^2', 'ds_Aggregate_Cumulative');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Net W/m^2', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Net W/m^2', 'ds_Medium_Solar');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Net W/m^2', 'ds_Variable_SolarRadiation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Net W/m^2', 'dt_Unit_WattPerSquareMeter');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Std W/m^2', 'ds_Aggregate_StandardDeviation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Std W/m^2', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Std W/m^2', 'ds_Medium_Solar');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Std W/m^2', 'ds_Variable_SolarRadiation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Std W/m^2', 'dt_Unit_WattPerSquareMeter');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total kJ/m^2', 'ds_Aggregate_Cumulative');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total kJ/m^2', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total kJ/m^2', 'ds_Medium_Solar');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total kJ/m^2', 'ds_Variable_SolarRadiation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total kJ/m^2', 'dt_Unit_KilojoulePerSquareMeter');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total kW/m^2', 'ds_Aggregate_Cumulative');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total kW/m^2', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total kW/m^2', 'ds_Medium_Solar');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total kW/m^2', 'ds_Variable_SolarRadiation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total kW/m^2', 'dt_Unit_KilowattPerSquareMeter');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total lux', 'ds_Aggregate_Cumulative');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total lux', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total lux', 'ds_Medium_Solar');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total lux', 'ds_Variable_SolarRadiation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total lux', 'dt_Unit_Lux');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total MJ/m^2', 'ds_Aggregate_Cumulative');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total MJ/m^2', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total MJ/m^2', 'ds_Medium_Solar');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total MJ/m^2', 'ds_Variable_SolarRadiation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total MJ/m^2', 'dt_Unit_MegajoulePerSquareMeter');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total W/m^2', 'ds_Aggregate_Cumulative');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total W/m^2', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total W/m^2', 'ds_Medium_Solar');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total W/m^2', 'ds_Variable_SolarRadiation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Solar Radiation Total W/m^2', 'dt_Unit_WattPerSquareMeter');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Direction Standard Deviation', 'ds_Aggregate_StandardDeviation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Direction Standard Deviation', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Direction Standard Deviation', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Direction Standard Deviation', 'ds_Variable_Direction');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Direction Standard Deviation', 'dt_Unit_DegreeAngle');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Avg MPH', 'ds_Aggregate_Average');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Avg MPH', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Avg MPH', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Avg MPH', 'ds_Variable_Velocity');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Avg MPH', 'dt_Unit_MilePerHour');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Avg MS', 'ds_Aggregate_Average');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Avg MS', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Avg MS', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Avg MS', 'ds_Variable_Velocity');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Avg MS', 'dt_Unit_MeterPerSecond');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Max MPH', 'ds_Aggregate_Maximum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Max MPH', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Max MPH', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Max MPH', 'ds_Variable_Velocity');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Max MPH', 'dt_Unit_MilePerHour');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Max MS', 'ds_Aggregate_Maximum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Max MS', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Max MS', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Max MS', 'ds_Variable_Velocity');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Max MS', 'dt_Unit_MeterPerSecond');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Min MPH', 'ds_Aggregate_Minimum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Min MPH', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Min MPH', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Min MPH', 'ds_Variable_Velocity');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Min MPH', 'dt_Unit_MilePerHour');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Min MS', 'ds_Aggregate_Minimum');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Min MS', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Min MS', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Min MS', 'ds_Variable_Velocity');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Min MS', 'dt_Unit_MeterPerSecond');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Stdev MPH', 'ds_Aggregate_StandardDeviation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Stdev MPH', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Stdev MPH', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Stdev MPH', 'ds_Variable_Velocity');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Stdev MPH', 'dt_Unit_MilePerHour');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Stdev MS', 'ds_Aggregate_StandardDeviation');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Stdev MS', 'ds_Function_Seasonal');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Stdev MS', 'ds_Medium_Air');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Stdev MS', 'ds_Variable_Velocity');
INSERT INTO `dendra_map_variables_tags` VALUES ('Wind Speed Stdev MS', 'dt_Unit_MeterPerSecond');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
